import { MeetingAgenda, AgendaSection } from '../types';

export function formatTimeRange(startMinutes: number, durationMinutes: number): string {
  const formatMin = (m: number) => {
    const hours = Math.floor(m / 60);
    const mins = m % 60;
    if (hours > 0) {
      return `${hours}h ${mins > 0 ? `${mins}m` : ''}`.trim();
    }
    return `${mins}m`;
  };

  const pad = (n: number) => n.toString().padStart(2, '0');
  const startH = Math.floor(startMinutes / 60);
  const startM = startMinutes % 60;
  const endMinutes = startMinutes + durationMinutes;
  const endH = Math.floor(endMinutes / 60);
  const endM = endMinutes % 60;

  return `${pad(startH)}:${pad(startM)} - ${pad(endH)}:${pad(endM)} (${durationMinutes} min)`;
}

export function calculateTimeline(sections: AgendaSection[]) {
  let elapsed = 0;
  return sections.map((section) => {
    const start = elapsed;
    elapsed += section.durationMinutes;
    return {
      ...section,
      startMinutes: start,
      endMinutes: elapsed,
      timeLabel: formatTimeRange(start, section.durationMinutes),
    };
  });
}

export function generateMarkdownAgenda(agenda: MeetingAgenda): string {
  let md = `# 📅 ${agenda.title}\n\n`;
  md += `**Meeting Objective:** ${agenda.meetingGoal}\n`;
  md += `**Total Duration:** ${agenda.totalDurationMinutes} minutes\n`;
  md += `**Meeting Type:** ${agenda.meetingType}\n`;
  md += `**Target Audience:** ${agenda.targetAudience}\n\n`;

  if (agenda.preReadHighlights && agenda.preReadHighlights.length > 0) {
    md += `## 📖 Pre-Read & Context\n`;
    agenda.preReadHighlights.forEach((p) => {
      md += `- ${p}\n`;
    });
    md += `\n`;
  }

  md += `## ⏱️ Agenda Timeline & Section Breakdown\n\n`;
  const timeline = calculateTimeline(agenda.sections);
  timeline.forEach((sec, idx) => {
    md += `### ${idx + 1}. ${sec.title} (${sec.durationMinutes} mins | ${sec.timeLabel})\n`;
    md += `**Category:** ${sec.category} ${sec.leadStakeholder ? `| **Lead:** ${sec.leadStakeholder}` : ''}\n\n`;
    md += `**Summary:** ${sec.summary}\n\n`;
    if (sec.keyDiscussionPoints && sec.keyDiscussionPoints.length > 0) {
      md += `**Key Discussion Points:**\n`;
      sec.keyDiscussionPoints.forEach((dp) => {
        md += `- ${dp}\n`;
      });
      md += `\n`;
    }
    md += `**Expected Outcome / Decision:** ${sec.expectedOutcome}\n\n`;
  });

  if (agenda.stakeholders && agenda.stakeholders.length > 0) {
    md += `## 👥 Stakeholders & Roles\n\n`;
    agenda.stakeholders.forEach((s) => {
      md += `- **${s.nameOrRole}** ${s.departmentOrTeam ? `(${s.departmentOrTeam})` : ''}: ${s.responsibility}`;
      if (s.keyInterestOrInput) {
        md += ` — *Input needed: ${s.keyInterestOrInput}*`;
      }
      md += `\n`;
    });
    md += `\n`;
  }

  if (agenda.actionItems && agenda.actionItems.length > 0) {
    md += `## ✅ Action Items & Follow-ups\n\n`;
    agenda.actionItems.forEach((a) => {
      md += `- [ ] **${a.task}** (Owner: @${a.owner} | Priority: ${a.priority}${a.suggestedDeadline ? ` | Due: ${a.suggestedDeadline}` : ''})\n`;
      if (a.context) {
        md += `  *${a.context}*\n`;
      }
    });
    md += `\n`;
  }

  if (agenda.keyRisksOrBlockers && agenda.keyRisksOrBlockers.length > 0) {
    md += `## ⚠️ Key Blockers & Risks\n\n`;
    agenda.keyRisksOrBlockers.forEach((r) => {
      md += `- ${r}\n`;
    });
    md += `\n`;
  }

  if (agenda.closingQuestionOrPrompt) {
    md += `## 🎯 Alignment Check / Closing Question\n\n> "${agenda.closingQuestionOrPrompt}"\n\n`;
  }

  md += `---\n*Generated by Meeting Agenda Crafter*`;
  return md;
}

export function generateEmailDraft(agenda: MeetingAgenda): string {
  let email = `Subject: Agenda: ${agenda.title} (${agenda.totalDurationMinutes} mins)\n\n`;
  email += `Hi team,\n\nHere is our structured agenda for the upcoming meeting on "${agenda.title}".\n\n`;
  email += `🎯 PRIMARY OBJECTIVE:\n${agenda.meetingGoal}\n\n`;

  if (agenda.preReadHighlights?.length) {
    email += `📖 PRE-READ HIGHLIGHTS:\n`;
    agenda.preReadHighlights.forEach((p) => {
      email += `• ${p}\n`;
    });
    email += `\n`;
  }

  email += `⏱️ TIMELINE & TOPICS (${agenda.totalDurationMinutes} mins total):\n`;
  const timeline = calculateTimeline(agenda.sections);
  timeline.forEach((sec, idx) => {
    email += `${idx + 1}. [${sec.durationMinutes}m] ${sec.title} (${sec.category})\n`;
    email += `   Lead: ${sec.leadStakeholder || 'Facilitator'}\n`;
    email += `   Goal: ${sec.expectedOutcome}\n`;
  });
  email += `\n`;

  if (agenda.actionItems?.length) {
    email += `📋 EXPECTED ACTION DELIVERABLES:\n`;
    agenda.actionItems.forEach((a) => {
      email += `• ${a.task} (Owner: ${a.owner}, Priority: ${a.priority})\n`;
    });
    email += `\n`;
  }

  email += `Looking forward to an efficient and productive session!\n\nBest regards,`;
  return email;
}

export function downloadCalendarICS(agenda: MeetingAgenda) {
  const title = agenda.title.replace(/[,;]/g, '');
  const description = generateEmailDraft(agenda).replace(/\n/g, '\\n');
  const now = new Date();
  // Schedule 24h from now as default
  const startTime = new Date(now.getTime() + 24 * 60 * 60 * 1000);
  const endTime = new Date(startTime.getTime() + agenda.totalDurationMinutes * 60 * 1000);

  const formatICSDate = (d: Date) =>
    d.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';

  const icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Meeting Agenda Crafter//EN',
    'CALSCALE:GREGORIAN',
    'BEGIN:VEVENT',
    `SUMMARY:${title}`,
    `DESCRIPTION:${description}`,
    `DTSTART:${formatICSDate(startTime)}`,
    `DTEND:${formatICSDate(endTime)}`,
    `STATUS:CONFIRMED`,
    'END:VEVENT',
    'END:VCALENDAR',
  ].join('\r\n');

  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
  const link = document.createElement('a');
  link.href = window.URL.createObjectURL(blob);
  link.setAttribute('download', `${title.toLowerCase().replace(/\s+/g, '_')}_agenda.ics`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
